/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Configuracion.ParametrosImpl;
import javax.swing.JFileChooser;

/**
 *
 * @author marti
 */
public class PantallaConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form PantallaConfiguracion
     */
    private Pantalla v;

    public Pantalla getV() {
        return v;
    }

    public void setV(Pantalla v) {
        this.v = v;
    }

    private final JFileChooser fc = new JFileChooser();
    private String path;
    private String pathModel;
    private ParametrosImpl parametrosImpl;

    public PantallaConfiguracion() {
        initComponents();

        parametrosImpl = ParametrosImpl.getParametrosImpl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        Ruta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Ruta1 = new javax.swing.JTextField();
        alinear = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        OK = new javax.swing.JTextField();
        SKIP = new javax.swing.JTextField();
        INSERT = new javax.swing.JTextField();
        alinear1 = new javax.swing.JButton();

        setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Path Modelo:");
        add(jLabel11);
        jLabel11.setBounds(54, 92, 116, 22);

        Ruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RutaMouseClicked(evt);
            }
        });
        add(Ruta);
        Ruta.setBounds(216, 90, 515, 26);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("COSTES DE LOS MOVIMIENTOS");
        add(jLabel1);
        jLabel1.setBounds(256, 206, 286, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Path Log:");
        add(jLabel12);
        jLabel12.setBounds(54, 144, 116, 22);

        Ruta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ruta1MouseClicked(evt);
            }
        });
        Ruta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ruta1ActionPerformed(evt);
            }
        });
        add(Ruta1);
        Ruta1.setBounds(216, 142, 515, 26);

        alinear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        alinear.setText("ALINEAR AD");
        alinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alinearActionPerformed(evt);
            }
        });
        add(alinear);
        alinear.setBounds(550, 470, 146, 31);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("OK:");
        add(jLabel13);
        jLabel13.setBounds(94, 284, 31, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("SELECCIONE MODELO Y LOG");
        add(jLabel2);
        jLabel2.setBounds(267, 26, 286, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("SKIP:");
        add(jLabel14);
        jLabel14.setBounds(555, 284, 56, 22);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("INSERT:");
        add(jLabel15);
        jLabel15.setBounds(308, 284, 71, 22);
        add(OK);
        OK.setBounds(143, 282, 101, 26);
        add(SKIP);
        SKIP.setBounds(617, 282, 114, 26);
        add(INSERT);
        INSERT.setBounds(385, 282, 110, 26);

        alinear1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        alinear1.setText("ALINEAR");
        alinear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alinear1ActionPerformed(evt);
            }
        });
        add(alinear1);
        alinear1.setBounds(361, 467, 146, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void RutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutaMouseClicked
        if (this.Ruta.isEnabled()) {
            if (fc.showOpenDialog(null) != JFileChooser.CANCEL_OPTION) {
                Ruta.setText(fc.getSelectedFile().getPath());
                this.pathModel = fc.getSelectedFile().toString();
            }
        }
    }//GEN-LAST:event_RutaMouseClicked

    private void Ruta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ruta1MouseClicked
        if (this.Ruta1.isEnabled()) {
            if (fc.showOpenDialog(null) != JFileChooser.CANCEL_OPTION) {
                Ruta1.setText(fc.getSelectedFile().getPath());
                this.path = fc.getSelectedFile().toString();
            }
        }
    }//GEN-LAST:event_Ruta1MouseClicked

    private void Ruta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ruta1ActionPerformed
        // TODO add your handling code here:
        this.getV().getContentPane().setVisible(false);
        PantallaAlgoritmo pl = new PantallaAlgoritmo(path, pathModel);
        pl.setVisible(true);
        pl.setV(this.getV());
        this.getV().setContentPane(pl);
        pl.alinear();
    }//GEN-LAST:event_Ruta1ActionPerformed

    private void alinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alinearActionPerformed

        this.getV().getContentPane().setVisible(false);
        PantallaAlgoritmo pl = new PantallaAlgoritmo(path, pathModel);
        pl.setVisible(true);
        pl.setV(this.getV());
        this.getV().setContentPane(pl);
        pl.alinear2();
    }//GEN-LAST:event_alinearActionPerformed

    private void alinear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alinear1ActionPerformed
        // TODO add your handling code here:

        this.getV().getContentPane().setVisible(false);
        PantallaAlgoritmo pl = new PantallaAlgoritmo(path, pathModel);
        pl.setVisible(true);
        pl.setV(this.getV());
        this.getV().setContentPane(pl);
        pl.alinear();
    }//GEN-LAST:event_alinear1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField INSERT;
    private javax.swing.JTextField OK;
    private javax.swing.JTextField Ruta;
    private javax.swing.JTextField Ruta1;
    private javax.swing.JTextField SKIP;
    private javax.swing.JButton alinear;
    private javax.swing.JButton alinear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
